@startuml
[*] --> EmptyNoMenu
EmptyNoMenu --> TextNoMenu: ReedlineEvent::Edit([InsertChar('l')])\nReedlineEvent::Edit([InsertChar('s')])\nReedlineEvent::Edit([InsertChar('s')])\nReedlineEvent::Edit([InsertChar('a')])
TextNoMenu : "ls a"
TextNoMenu --> TextWithMenu1: TAB\nReedlineEvent::UntilFound([Menu("completion_menu"), MenuNext])\nReedlineEvent::Menu\nMenuEvent::Activate
TextWithMenu1: "ls a"\naaa.txt | abb.txt
TextWithMenu1 --> TextWithMenu2: a\nReedlineEvent::Edit([InsertChar('a')])
TextWithMenu2: "ls aa"\naaa.txt | abb.txt
TextWithMenu2 -> TextWithMenu2: TAB\nReedlineEvent::UntilFound([Menu("completion_menu"), MenuNext])\nReedlineEvent::Menu\nReedlineEvent::MenuNext
@enduml